### ISSUE TITLE
Extract the entities docs and copy them to docs.vuestorefront.io

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/storefront-integration-sdk#14]
Let's move the product/attributes/categories/taxrules specs from https://github.com/DivanteLtd/vue-storefront-integration-boilerplate/blob/master/1.%20Expose%20the%20API%20endpoints%20required%20by%20VS/Required%20API%20specification.md to http://docs.vuestorefront.io

**Comment by janmyszkier** [comment]
small update here, this is now in
https://github.com/DivanteLtd/storefront-integration-sdk/blob/tutorial/Format-attribute.md
https://github.com/DivanteLtd/storefront-integration-sdk/blob/tutorial/Format-category.md
and
https://github.com/DivanteLtd/storefront-integration-sdk/blob/tutorial/Format-product.md
and MAYBE https://github.com/DivanteLtd/storefront-integration-sdk/blob/tutorial/Prices%20how-to.md

but I'm not sure if this ticket is still worth doing.

**Comment by janmyszkier** [comment]
confirmed in https://discordapp.com/channels/770285988244750366/786223999138004992/889765611440328714 that it isn't. 
Closing
